// src/routes/login/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import Breadcrumb from '$lib/components/ui/breadcrumb/Breadcrumb.svelte';

	import Lock from '@lucide/svelte/icons/lock';
	import Mail from '@lucide/svelte/icons/mail';
	import User from '@lucide/svelte/icons/user';
	import ArrowRight from '@lucide/svelte/icons/arrow-right';
	import Loader2 from '@lucide/svelte/icons/loader-2';
	import AlertCircle from '@lucide/svelte/icons/alert-circle';
	import Sparkles from '@lucide/svelte/icons/sparkles';

	let mode = $state<'login' | 'register'>('login');

	// Form fields
	let loginEmail = $state('dian.sastro@example.com');
	let loginPassword = $state('password123');

	let regName = $state('');
	let regEmail = $state('');
	let regPassword = $state('');
	let regConfirmPassword = $state('');

	// State
	let isLoading = $state(false);
	let errorMessage = $state('');
	let successMessage = $state('');

	let redirectUrl = $derived($page.url.searchParams.get('redirect') || '/akun');

	async function handleLogin(e: SubmitEvent) {
		e.preventDefault();
		errorMessage = '';
		isLoading = true;

		try {
			const res = await fetch('/api/auth/login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					email: loginEmail,
					password: loginPassword
				})
			});

			const data = await res.json();
			if (!res.ok) {
				throw new Error(data.error || 'Gagal masuk');
			}

			goto(redirectUrl);
		} catch (err: any) {
			errorMessage = err.message || 'Terjadi kesalahan saat masuk';
		} finally {
			isLoading = false;
		}
	}

	async function handleRegister(e: SubmitEvent) {
		e.preventDefault();
		errorMessage = '';

		if (regPassword !== regConfirmPassword) {
			errorMessage = 'Konfirmasi kata sandi tidak cocok.';
			return;
		}

		isLoading = true;

		try {
			const res = await fetch('/api/auth/register', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					name: regName,
					email: regEmail,
					password: regPassword
				})
			});

			const data = await res.json();
			if (!res.ok) {
				throw new Error(data.error || 'Pendaftaran gagal');
			}

			goto(redirectUrl);
		} catch (err: any) {
			errorMessage = err.message || 'Terjadi kesalahan saat mendaftar';
		} finally {
			isLoading = false;
		}
	}

	function handleDemoLogin() {
		loginEmail = 'dian.sastro@example.com';
		loginPassword = 'password123';
		const form = document.getElementById('login-form') as HTMLFormElement;
		if (form) form.requestSubmit();
	}
</script>

<svelte:head>
	<title>{mode === 'login' ? 'Masuk ke Akun' : 'Daftar Akun Baru'} | Maison Lumina</title>
	<meta name="description" content="Masuk atau daftarkan akun Anda di Maison Lumina Atelier & Mebel." />
</svelte:head>

<div class="min-h-screen bg-[#F7F3EC] py-6 sm:py-12">
	<div class="mx-auto max-w-md px-4 sm:px-6">
		<!-- Breadcrumb -->
		<div class="mb-6">
			<Breadcrumb
				items={[
					{ label: 'Beranda', href: '/' },
					{ label: mode === 'login' ? 'Masuk Akun' : 'Daftar Akun' }
				]}
			/>
		</div>

		<!-- Main Card Container -->
		<div class="overflow-hidden rounded-3xl border border-[#E8DFD0] bg-white p-7 sm:p-9 shadow-sm">
			<!-- Header Monogram -->
			<div class="text-center">
				<div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#1F1810] text-[#F7F3EC] font-serif text-lg font-bold shadow-sm">
					ML
				</div>
				<h1 class="mt-4 font-serif text-2xl font-bold text-[#1F1810] sm:text-3xl">
					{mode === 'login' ? 'Selamat Datang Kembali' : 'Bergabung Bersama Kami'}
				</h1>
				<p class="mt-1.5 text-xs text-stone-600">
					{mode === 'login'
						? 'Masuk untuk mengelola pesanan & preferensi hunian Anda.'
						: 'Daftarkan diri Anda untuk menikmati kurasi furnitur eksklusif.'}
				</p>
			</div>

			<!-- Tab Switcher -->
			<div class="mt-6 grid grid-cols-2 rounded-xl bg-[#F7F3EC] p-1 border border-[#E8DFD0]/60">
				<button
					type="button"
					onclick={() => {
						mode = 'login';
						errorMessage = '';
					}}
					class="rounded-lg py-2 text-xs font-semibold transition-all {mode === 'login' ? 'bg-white text-[#1F1810] shadow-xs' : 'text-stone-600 hover:text-[#1F1810]'}"
				>
					Masuk (Login)
				</button>
				<button
					type="button"
					onclick={() => {
						mode = 'register';
						errorMessage = '';
					}}
					class="rounded-lg py-2 text-xs font-semibold transition-all {mode === 'register' ? 'bg-white text-[#1F1810] shadow-xs' : 'text-stone-600 hover:text-[#1F1810]'}"
				>
					Daftar Akun
				</button>
			</div>

			<!-- Error / Success Alert -->
			{#if errorMessage}
				<div class="mt-5 rounded-xl bg-rose-50 border border-rose-200 p-3.5 flex items-start gap-2.5 text-xs text-rose-700 animate-in fade-in">
					<AlertCircle class="h-4 w-4 shrink-0 text-rose-600 mt-0.5" />
					<span>{errorMessage}</span>
				</div>
			{/if}

			{#if mode === 'login'}
				<!-- Login Form -->
				<form id="login-form" onsubmit={handleLogin} class="mt-6 space-y-4">
					<div>
						<label for="login-email" class="block text-xs font-medium text-stone-700 mb-1">
							Alamat Email
						</label>
						<div class="relative">
							<input
								id="login-email"
								type="email"
								required
								bind:value={loginEmail}
								placeholder="nama@domain.com"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<Mail class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<div>
						<div class="flex items-center justify-between mb-1">
							<label for="login-password" class="text-xs font-medium text-stone-700">
								Kata Sandi
							</label>
						</div>
						<div class="relative">
							<input
								id="login-password"
								type="password"
								required
								bind:value={loginPassword}
								placeholder="••••••••"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<Lock class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<button
						type="submit"
						disabled={isLoading}
						class="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1F1810] py-3 text-xs font-semibold text-white shadow-sm transition-all hover:bg-[#B5652F] active:scale-[0.98] disabled:opacity-50"
					>
						{#if isLoading}
							<Loader2 class="h-4 w-4 animate-spin text-white" />
							<span>Memproses Masuk...</span>
						{:else}
							<span>Masuk ke Akun</span>
							<ArrowRight class="h-3.5 w-3.5" />
						{/if}
					</button>

					<!-- Demo Quick Login Helper -->
					<div class="pt-4 border-t border-[#E8DFD0]/60">
						<button
							type="button"
							onclick={handleDemoLogin}
							class="flex w-full items-center justify-center gap-2 rounded-xl border border-[#B5652F]/40 bg-[#B5652F]/5 py-2.5 text-xs font-semibold text-[#B5652F] hover:bg-[#B5652F]/10 transition-colors"
						>
							<Sparkles class="h-3.5 w-3.5" />
							<span>Masuk Cepat Demo VIP (Dian Sastrowardoyo)</span>
						</button>
					</div>
				</form>
			{:else}
				<!-- Register Form -->
				<form onsubmit={handleRegister} class="mt-6 space-y-4">
					<div>
						<label for="reg-name" class="block text-xs font-medium text-stone-700 mb-1">
							Nama Lengkap *
						</label>
						<div class="relative">
							<input
								id="reg-name"
								type="text"
								required
								bind:value={regName}
								placeholder="Contoh: Dian Sastrowardoyo"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<User class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<div>
						<label for="reg-email" class="block text-xs font-medium text-stone-700 mb-1">
							Alamat Email *
						</label>
						<div class="relative">
							<input
								id="reg-email"
								type="email"
								required
								bind:value={regEmail}
								placeholder="nama@domain.com"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<Mail class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<div>
						<label for="reg-password" class="block text-xs font-medium text-stone-700 mb-1">
							Kata Sandi (Min. 6 Karakter) *
						</label>
						<div class="relative">
							<input
								id="reg-password"
								type="password"
								required
								minlength="6"
								bind:value={regPassword}
								placeholder="••••••••"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<Lock class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<div>
						<label for="reg-confirm-password" class="block text-xs font-medium text-stone-700 mb-1">
							Konfirmasi Kata Sandi *
						</label>
						<div class="relative">
							<input
								id="reg-confirm-password"
								type="password"
								required
								minlength="6"
								bind:value={regConfirmPassword}
								placeholder="••••••••"
								class="w-full rounded-xl border border-[#E8DFD0] pl-10 pr-3 py-2.5 text-xs text-[#1F1810] focus:border-[#B5652F] focus:outline-none"
							/>
							<Lock class="h-4 w-4 text-stone-400 absolute left-3.5 top-3 pointer-events-none" />
						</div>
					</div>

					<button
						type="submit"
						disabled={isLoading}
						class="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-[#B5652F] py-3 text-xs font-semibold text-white shadow-sm transition-all hover:bg-[#9E5424] active:scale-[0.98] disabled:opacity-50"
					>
						{#if isLoading}
							<Loader2 class="h-4 w-4 animate-spin text-white" />
							<span>Mendaftarkan Akun...</span>
						{:else}
							<span>Daftar Akun Baru</span>
							<ArrowRight class="h-3.5 w-3.5" />
						{/if}
					</button>
				</form>
			{/if}
		</div>
	</div>
</div>

// src/app/login/page.tsx
"use client";

import React, { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { signIn } from "next-auth/react";
import { Lock, AlertCircle, ShoppingBag, Sparkles, CheckCircle2 } from "lucide-react";
import { registerAction } from "@/lib/actions/register";

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const redirectUrl = searchParams.get("redirect") || "/akun";

  const [activeTab, setActiveTab] = useState<"masuk" | "daftar">("masuk");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);
    setIsLoading(true);

    try {
      if (activeTab === "masuk") {
        const res = await signIn("credentials", {
          email,
          password,
          redirect: false,
        });

        if (res?.error) {
          setErrorMsg("Email atau kata sandi salah");
          setIsLoading(false);
        } else {
          router.push(redirectUrl);
          router.refresh();
        }
      } else {
        // Register form validation
        if (password.length < 8) {
          setErrorMsg("Kata sandi harus minimal 8 karakter");
          setIsLoading(false);
          return;
        }

        const regRes = await registerAction(name, email, password);
        if (!regRes.success) {
          setErrorMsg(regRes.error || "Gagal membuat akun");
          setIsLoading(false);
          return;
        }

        // Auto sign in after registration
        const signInRes = await signIn("credentials", {
          email,
          password,
          redirect: false,
        });

        if (signInRes?.error) {
          setErrorMsg("Akun berhasil dibuat. Silakan masuk dengan akun baru Anda.");
          setActiveTab("masuk");
          setIsLoading(false);
        } else {
          router.push(redirectUrl);
          router.refresh();
        }
      }
    } catch (err) {
      console.error("Auth submit error:", err);
      setErrorMsg("Terjadi gangguan saat menghubungi server. Silakan coba kembali.");
      setIsLoading(false);
    }
  };

  const handleFillDemo = () => {
    setActiveTab("masuk");
    setEmail("dian.sastro@example.com");
    setPassword("demo1234");
    setErrorMsg(null);
  };

  return (
    <div className="page-fade-in relative min-h-[85vh]">
      {/* Background */}
      <div className="absolute inset-0 z-0">
        <img
          src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=60"
          alt="Interior Japandi"
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-brand-bg/70 backdrop-blur-md" />
      </div>

      {/* Card */}
      <div className="relative z-10 flex items-center justify-center px-4 py-12 sm:py-16">
        <div className="w-full max-w-md bg-white rounded-2xl shadow-elevated p-8 border border-brand-border">
          {/* Header */}
          <div className="text-center mb-6">
            <p className="text-xs tracking-[0.2em] uppercase text-brand-accent font-semibold mb-1">
              MAISON LUMINA ATELIER
            </p>
            <h1 className="font-serif text-2xl sm:text-3xl font-bold text-brand-dark">
              {activeTab === "masuk" ? "Selamat Datang" : "Buat Akun Baru"}
            </h1>
            <p className="text-xs sm:text-sm text-brand-muted mt-1.5">
              {redirectUrl === "/keranjang"
                ? "Silakan masuk untuk melanjutkan proses pemesanan furniture kurasi Anda."
                : "Akses riwayat pesanan, status pengiriman armada, dan wishlist eksklusif."}
            </p>
          </div>

          {/* Notice Banner if redirected from checkout */}
          {redirectUrl === "/keranjang" && (
            <div className="mb-5 p-3.5 bg-brand-soft border border-brand-accent/30 rounded-xl flex items-start gap-2.5 text-xs text-brand-dark">
              <ShoppingBag size={16} className="text-brand-accent shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold block">Checkout Membutuhkan Akun</span>
                Silakan masuk atau daftar terlebih dahulu untuk melanjutkan pesanan Anda ke tahap konfirmasi.
              </div>
            </div>
          )}

          {/* Error Message */}
          {errorMsg && (
            <div className="mb-5 p-3.5 bg-red-50 border border-red-200 rounded-xl flex items-center gap-2.5 text-xs text-red-700">
              <AlertCircle size={16} className="shrink-0 text-red-500" />
              <span>{errorMsg}</span>
            </div>
          )}

          {/* Tabs */}
          <div className="flex mb-6 bg-brand-bg rounded-lg p-1">
            <button
              type="button"
              onClick={() => {
                setActiveTab("masuk");
                setErrorMsg(null);
              }}
              className={`flex-1 py-2 text-xs font-semibold rounded-md transition-colors ${
                activeTab === "masuk"
                  ? "bg-brand-dark text-white shadow-sm"
                  : "text-brand-muted hover:text-brand-dark"
              }`}
            >
              Masuk
            </button>
            <button
              type="button"
              onClick={() => {
                setActiveTab("daftar");
                setErrorMsg(null);
              }}
              className={`flex-1 py-2 text-xs font-semibold rounded-md transition-colors ${
                activeTab === "daftar"
                  ? "bg-brand-dark text-white shadow-sm"
                  : "text-brand-muted hover:text-brand-dark"
              }`}
            >
              Daftar Akun
            </button>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            {activeTab === "daftar" && (
              <div>
                <label className="text-xs font-medium text-brand-dark mb-1 block">
                  Nama Lengkap *
                </label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Contoh: Dian Sastrowardoyo"
                  className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg bg-white focus:outline-none focus:border-brand-accent"
                  required
                />
              </div>
            )}
            <div>
              <label className="text-xs font-medium text-brand-dark mb-1 block">
                Alamat Email *
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="nama@domain.com"
                className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg bg-white focus:outline-none focus:border-brand-accent"
                required
              />
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-medium text-brand-dark">Kata Sandi *</label>
                {activeTab === "daftar" && (
                  <span className="text-[11px] text-accent font-medium">
                    Minimal 8 karakter
                  </span>
                )}
              </div>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                minLength={activeTab === "daftar" ? 8 : 1}
                className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg bg-white focus:outline-none focus:border-brand-accent"
                required
              />
              {activeTab === "daftar" && (
                <p className="text-[10px] text-brand-muted mt-1">
                  Gunakan kombinasi huruf dan angka minimal 8 karakter untuk keamanan akun Anda.
                </p>
              )}
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-3 bg-brand-dark text-white text-xs font-bold uppercase tracking-wider rounded-lg hover:bg-brand-hoverDark transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-sm flex items-center justify-center gap-2"
            >
              {isLoading ? (
                <>
                  <div className="animate-spin rounded-full h-3.5 w-3.5 border-b-2 border-white" />
                  <span>Memproses...</span>
                </>
              ) : activeTab === "masuk" ? (
                "MASUK KE AKUN"
              ) : (
                "DAFTAR AKUN BARU"
              )}
            </button>
          </form>

          {/* Quick Demo Fill Helper */}
          <div className="mt-5 pt-4 border-t border-brand-border">
            <button
              type="button"
              onClick={handleFillDemo}
              className="w-full py-2 px-3 bg-brand-soft/60 hover:bg-brand-soft text-brand-dark rounded-lg text-xs font-medium flex items-center justify-center gap-1.5 transition-colors border border-brand-border/60"
            >
              <Sparkles size={13} className="text-brand-accent" />
              <span>
                Gunakan Akun Demo: <strong>dian.sastro@example.com</strong>
              </span>
            </button>
          </div>

          {/* Security badge */}
          <div className="flex items-center justify-center gap-2 mt-4 text-[11px] text-brand-muted">
            <Lock size={12} />
            <span>Enkripsi Aman &amp; Terproteksi NextAuth.js</span>
          </div>
        </div>
      </div>
    </div>
  );
}
