// src/components/product/ProductCard.tsx
"use client";

import * as React from "react";
import Link from "next/link";
import { Heart } from "lucide-react";
import { formatRupiah } from "@/lib/utils";
import { ProductWithDetails } from "@/lib/queries/product";
import { useWishlistStore } from "@/store/wishlistStore";

interface ProductCardProps {
  product: any;
  showQuickAdd?: boolean;
}

export default function ProductCard({ product }: ProductCardProps) {
  const [mounted, setMounted] = React.useState(false);
  const { toggleWishlist, isWishlisted } = useWishlistStore();

  React.useEffect(() => {
    setMounted(true);
  }, []);

  const isHeartActive = mounted ? isWishlisted(product.id) : false;

  const primaryImage =
    product.images && product.images.length > 0
      ? typeof product.images[0] === "string"
        ? product.images[0]
        : product.images[0].url
      : "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80";

  const handleWishlist = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    try {
      await toggleWishlist({
        productId: product.id,
        name: product.name,
        slug: product.slug,
        image: primaryImage,
        price: product.price,
        category: product.category?.name || "Furnitur",
        material: product.material,
        status: product.status,
        description: product.description,
        rating: product.rating,
      });
    } catch (err) {
      console.error("Wishlist toggle error:", err);
    }
  };

  // Filter color swatches from variants
  const colorVariants =
    product.variants?.filter((v: any) => v.type === "warna_kain") || [];
  const displaySwatches = colorVariants.slice(0, 3);
  const remainingSwatchesCount = colorVariants.length - 3;

  const isReady = product.status === "Ready Stock";

  return (
    <div className="group relative bg-white rounded-xl overflow-hidden border border-border-soft hover:shadow-card transition-all duration-300 flex flex-col">
      {/* Image & Badges */}
      <div className="relative aspect-[4/5] w-full overflow-hidden bg-background">
        <Link href={`/koleksi/${product.slug}`} className="block w-full h-full">
          <img
            src={primaryImage}
            alt={product.images[0]?.altText || product.name}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
          />
        </Link>

        {/* Badge Status */}
        <div className="absolute top-3 left-3 pointer-events-none">
          <span
            className={`px-2.5 py-1 text-[10px] sm:text-xs font-semibold tracking-wide rounded-md uppercase ${
              isReady
                ? "bg-dark/90 text-white backdrop-blur-sm"
                : "bg-accent text-white"
            }`}
          >
            {product.status}
          </span>
        </div>

        {/* Wishlist Button */}
        <button
          type="button"
          onClick={handleWishlist}
          className={`absolute top-3 right-3 w-8 h-8 rounded-full flex items-center justify-center transition-all ${
            isHeartActive
              ? "bg-accent text-white shadow-sm"
              : "bg-white/90 text-text-secondary hover:bg-white hover:text-dark shadow-sm"
          }`}
          aria-label={isHeartActive ? "Hapus dari Wishlist" : "Tambah ke Wishlist"}
        >
          <Heart
            size={16}
            fill={isHeartActive ? "currentColor" : "none"}
            className="transition-transform active:scale-125"
          />
        </button>
      </div>

      {/* Info Container */}
      <div className="p-4 sm:p-5 flex-1 flex flex-col justify-between">
        <div>
          {/* Category • Material */}
          <p className="text-[10px] sm:text-[11px] uppercase tracking-wider text-text-secondary font-medium mb-1 line-clamp-1">
            {product.category?.name || "Furnitur"}
            {product.material ? ` • ${product.material}` : ""}
          </p>

          {/* Product Name */}
          <Link href={`/koleksi/${product.slug}`} className="block group-hover:text-accent transition-colors">
            <h3 className="font-serif text-base sm:text-lg font-bold text-dark mb-2 line-clamp-1">
              {product.name}
            </h3>
          </Link>
        </div>

        {/* Price & Color Swatches */}
        <div className="flex items-center justify-between pt-2 border-t border-border-soft/60 mt-2">
          <p className="font-sans text-base sm:text-lg font-bold text-dark">
            {formatRupiah(product.price)}
          </p>

          {/* Swatches */}
          {displaySwatches.length > 0 && (
            <div className="flex items-center gap-1">
              {displaySwatches.map((variant: any) => (
                <span
                  key={variant.id}
                  title={variant.label}
                  className="w-3.5 h-3.5 sm:w-4 sm:h-4 rounded-full border border-border-soft shadow-xs inline-block"
                  style={{ backgroundColor: variant.hexOrSwatch || "#D3C5B4" }}
                />
              ))}
              {remainingSwatchesCount > 0 && (
                <span className="text-[10px] text-text-secondary font-semibold ml-0.5">
                  +{remainingSwatchesCount}
                </span>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/lib/components/product/ProductCard.svelte
<script lang="ts">
	import type { Product } from '$lib/types';
	import { cartStore } from '$lib/stores/cart.svelte';
	import { wishlistStore } from '$lib/stores/wishlist.svelte';
	import { formatRupiah } from '$lib/utils';
	import { Badge } from '$lib/components/ui/badge';

	import Heart from '@lucide/svelte/icons/heart';
	import ShoppingBag from '@lucide/svelte/icons/shopping-bag';
	import Star from '@lucide/svelte/icons/star';
	import Check from '@lucide/svelte/icons/check';

	let { product }: { product: Product } = $props();

	let addedFeedback = $state(false);

	function handleAddToCart(e: MouseEvent) {
		e.preventDefault();
		e.stopPropagation();
		cartStore.addItem({
			productId: product.id,
			variantId: product.variants?.[0]?.id || null,
			name: product.name,
			image: product.images[0]?.url || '',
			unitPrice: product.price,
			qty: 1,
			maxStock: product.variants?.[0]?.stock || 20,
			material: product.material,
			variantLabel: product.variants?.[0]?.label || undefined,
			slug: product.slug
		});
		addedFeedback = true;
		setTimeout(() => { addedFeedback = false; }, 1500);
	}

	function handleToggleWishlist(e: MouseEvent) {
		e.preventDefault();
		e.stopPropagation();
		wishlistStore.toggleWishlist({
			id: product.id,
			productId: product.id,
			name: product.name,
			slug: product.slug,
			image: product.images[0]?.url || '',
			price: product.price,
			material: product.material,
			category: product.categoryName,
			status: product.status,
			rating: product.rating,
			colorSwatches: product.colorSwatches
		});
	}

	let isWishlisted = $derived(wishlistStore.isWishlisted(product.id));
</script>

<a
	href={`/produk/${product.slug}`}
	class="group bg-white rounded-xl border border-border/80 overflow-hidden shadow-sm hover:shadow-lg transition-all flex flex-col"
>
	<!-- Image -->
	<div class="relative aspect-[4/5] overflow-hidden bg-sand/20">
		<img
			src={product.images[0]?.url}
			alt={product.name}
			class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
			loading="lazy"
		/>

		<!-- Status Badge -->
		{#if product.status}
			<div class="absolute top-3 left-3">
				<Badge class="bg-espresso/90 text-stone-warm text-[10px] font-medium tracking-wide backdrop-blur-sm shadow-sm">
					{product.status}
				</Badge>
			</div>
		{/if}

		<!-- Wishlist Button -->
		<button
			type="button"
			onclick={handleToggleWishlist}
			class="absolute top-3 right-3 p-2 rounded-full bg-white/90 backdrop-blur-sm border border-border shadow-sm hover:bg-white hover:scale-110 transition-all"
			aria-label={isWishlisted ? 'Hapus dari wishlist' : 'Simpan ke wishlist'}
		>
			<Heart
				class={`w-4 h-4 transition-colors ${isWishlisted ? 'fill-terracotta text-terracotta' : 'text-espresso/70'}`}
			/>
		</button>

		<!-- Color Swatches Overlay -->
		{#if product.colorSwatches && product.colorSwatches.length > 0}
			<div class="absolute bottom-3 left-3 flex items-center gap-1">
				{#each product.colorSwatches.slice(0, 4) as hex}
					<span
						class="w-4 h-4 rounded-full border-2 border-white shadow-sm"
						style="background-color: {hex};"
					></span>
				{/each}
				{#if product.colorSwatches.length > 4}
					<span class="text-[10px] text-white/90 font-medium bg-black/40 backdrop-blur-sm px-1.5 py-0.5 rounded-full">
						+{product.colorSwatches.length - 4}
					</span>
				{/if}
			</div>
		{/if}
	</div>

	<!-- Info -->
	<div class="p-4 flex-1 flex flex-col justify-between space-y-2.5">
		<div>
			<div class="flex items-center justify-between text-[11px] text-muted-foreground mb-1">
				<span class="truncate">{product.categoryName || product.room || 'Mebel'}</span>
				{#if product.rating}
					<div class="flex items-center gap-1 text-amber-600 font-medium shrink-0">
						<Star class="w-3 h-3 fill-amber-500 text-amber-500" />
						<span>{product.rating}</span>
						<span class="text-muted-foreground/60">({product.reviewCount})</span>
					</div>
				{/if}
			</div>

			<h3 class="font-serif font-semibold text-sm text-espresso line-clamp-2 group-hover:text-terracotta transition-colors leading-snug">
				{product.name}
			</h3>

			<p class="text-[11px] text-muted-foreground line-clamp-1 mt-0.5">
				{product.material}
			</p>
		</div>

		<div class="pt-2 border-t border-border/60 flex items-center justify-between gap-1.5 sm:gap-2">
			<span class="font-semibold text-xs sm:text-sm text-espresso truncate">
				{formatRupiah(product.price)}
			</span>

			<button
				type="button"
				onclick={handleAddToCart}
				class={`inline-flex items-center justify-center gap-1 h-8 px-2 sm:px-3 text-xs font-medium rounded-md transition-all shrink-0 ${
					addedFeedback
						? 'bg-emerald-600 text-white scale-95'
						: 'bg-espresso hover:bg-terracotta text-white'
				}`}
				aria-label={`Tambah ${product.name} ke keranjang`}
			>
				{#if addedFeedback}
					<Check class="w-3.5 h-3.5" />
					<span class="hidden min-[380px]:inline">Masuk</span>
				{:else}
					<ShoppingBag class="w-3.5 h-3.5" />
					<span class="hidden min-[380px]:inline">+ Cart</span>
				{/if}
			</button>
		</div>
	</div>
</a>
