// src/routes/akun/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { formatRupiah, formatDateId } from '$lib/utils';
	import Breadcrumb from '$lib/components/ui/breadcrumb/Breadcrumb.svelte';
	import { Badge } from '$lib/components/ui/badge';
	import { goto } from '$app/navigation';

	import { cartStore } from '$lib/stores/cart.svelte';

	import User from '@lucide/svelte/icons/user';
	import Package from '@lucide/svelte/icons/package';
	import MapPin from '@lucide/svelte/icons/map-pin';
	import Sparkles from '@lucide/svelte/icons/sparkles';
	import LogOut from '@lucide/svelte/icons/log-out';
	import ArrowRight from '@lucide/svelte/icons/arrow-right';
	import Clock from '@lucide/svelte/icons/clock';
	import Phone from '@lucide/svelte/icons/phone';
	import ShieldCheck from '@lucide/svelte/icons/shield-check';
	import Wrench from '@lucide/svelte/icons/wrench';
	import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
	import Check from '@lucide/svelte/icons/check';

	let { data }: { data: PageData } = $props();
	let user = $derived(data.user);
	let orders = $derived(data.orders || []);
	let addresses = $derived(data.addresses || []);

	let activeTab = $state<'orders' | 'addresses' | 'concierge'>('orders');
	let reorderSuccessMsg = $state('');

	function handleReorderItem(item: any) {
		cartStore.addItem({
			productId: item.productId,
			variantId: item.variantId || null,
			name: item.product?.name || 'Item Furnitur',
			unitPrice: item.product?.price || item.priceAtOrder,
			image: item.product?.images?.[0]?.url || '',
			variantLabel: item.variantLabel || undefined,
			qty: item.qty || 1,
			maxStock: 99,
			slug: item.product?.slug
		});
		reorderSuccessMsg = `"${item.product?.name || 'Item'}" berhasil ditambahkan ke keranjang belanja.`;
		setTimeout(() => {
			reorderSuccessMsg = '';
		}, 3500);
	}

	function handleReorderAll(order: any) {
		const itemsToAdd = order.items.map((item: any) => ({
			productId: item.productId,
			variantId: item.variantId || null,
			name: item.product?.name || 'Item Furnitur',
			unitPrice: item.product?.price || item.priceAtOrder,
			image: item.product?.images?.[0]?.url || '',
			variantLabel: item.variantLabel || undefined,
			qty: item.qty || 1,
			maxStock: 99,
			slug: item.product?.slug
		}));
		cartStore.addMultipleItems(itemsToAdd);
		goto('/keranjang');
	}

	async function handleLogout() {
		try {
			await fetch('/api/auth/logout', { method: 'POST' });
			goto('/login');
		} catch (err) {
			console.error('Logout error:', err);
		}
	}
</script>

<svelte:head>
	<title>Akun Saya &amp; Riwayat Pesanan | Maison Lumina</title>
	<meta name="description" content="Kelola profil, buku alamat, dan pantau riwayat pesanan furnitur Anda di Maison Lumina." />
</svelte:head>

<div class="min-h-screen bg-[#F7F3EC] py-6 sm:py-10">
	<div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
		<!-- Breadcrumb -->
		<div class="mb-6">
			<Breadcrumb
				items={[
					{ label: 'Beranda', href: '/' },
					{ label: 'Akun Saya' }
				]}
			/>
		</div>

		<!-- User Profile Header Card -->
		<div class="rounded-3xl border border-[#E8DFD0] bg-white p-5 sm:p-8 shadow-sm">
			<div class="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
				<!-- Left Profile Info -->
				<div class="flex items-center gap-3.5 sm:gap-4">
					<div class="flex h-14 w-14 sm:h-20 sm:w-20 items-center justify-center rounded-full bg-[#1F1810] text-[#F7F3EC] font-serif text-xl sm:text-2xl font-bold shadow-md shrink-0">
						{user.name.split(' ').map((n: string) => n[0]).slice(0, 2).join('')}
					</div>
					<div>
						<div class="flex flex-wrap items-center gap-2">
							<h1 class="font-serif text-xl sm:text-3xl font-bold text-[#1F1810]">
								{user.name}
							</h1>
							<Badge class="bg-amber-100 text-amber-900 border-none px-2.5 py-0.5 text-xs font-semibold">
								<Sparkles class="h-3 w-3 mr-1 text-amber-700 inline" />
								Member {user.tier || 'VIP'}
							</Badge>
						</div>
						<p class="text-xs text-stone-500 mt-1">
							{user.email} • Bergabung sejak {user.createdAt ? new Date(user.createdAt).getFullYear() : 2024}
						</p>
					</div>
				</div>

				<!-- Right Loyalty & Actions -->
				<div class="flex items-center justify-between sm:justify-end gap-3 sm:gap-4 border-t border-[#E8DFD0]/60 pt-4 sm:border-0 sm:pt-0">
					<div class="rounded-2xl border border-[#E8DFD0] bg-[#F7F3EC] px-3.5 sm:px-4 py-2 sm:py-2.5 text-left sm:text-right">
						<span class="text-[9px] sm:text-[10px] font-semibold uppercase tracking-wider text-stone-500 block">
							Poin Loyalitas
						</span>
						<span class="font-serif text-base sm:text-lg font-bold text-[#B5652F]">
							{user.loyaltyPoints?.toLocaleString('id-ID') || 0} Poin
						</span>
					</div>

					<button
						type="button"
						onclick={handleLogout}
						class="flex items-center gap-1.5 rounded-xl border border-[#E8DFD0] bg-white px-3.5 py-2.5 text-xs font-semibold text-stone-600 hover:border-rose-300 hover:text-rose-600 transition-colors shadow-xs"
						title="Keluar dari akun"
					>
						<LogOut class="h-4 w-4" />
						<span>Keluar</span>
					</button>
				</div>
			</div>

			<!-- Navigation Tabs -->
			<div class="mt-6 sm:mt-8 flex gap-2 border-t border-[#E8DFD0] pt-4 overflow-x-auto scrollbar-none flex-nowrap pb-1">
				<button
					type="button"
					onclick={() => (activeTab = 'orders')}
					class="flex items-center gap-2 rounded-xl px-3.5 sm:px-4 py-2 text-xs font-semibold whitespace-nowrap shrink-0 transition-all {activeTab === 'orders' ? 'bg-[#1F1810] text-white shadow-sm' : 'text-stone-600 hover:bg-[#F7F3EC]'}"
				>
					<Package class="h-4 w-4" />
					<span>Riwayat Pesanan ({orders.length})</span>
				</button>

				<button
					type="button"
					onclick={() => (activeTab = 'addresses')}
					class="flex items-center gap-2 rounded-xl px-3.5 sm:px-4 py-2 text-xs font-semibold whitespace-nowrap shrink-0 transition-all {activeTab === 'addresses' ? 'bg-[#1F1810] text-white shadow-sm' : 'text-stone-600 hover:bg-[#F7F3EC]'}"
				>
					<MapPin class="h-4 w-4" />
					<span>Buku Alamat</span>
				</button>

				<button
					type="button"
					onclick={() => (activeTab = 'concierge')}
					class="flex items-center gap-2 rounded-xl px-3.5 sm:px-4 py-2 text-xs font-semibold whitespace-nowrap shrink-0 transition-all {activeTab === 'concierge' ? 'bg-[#1F1810] text-white shadow-sm' : 'text-stone-600 hover:bg-[#F7F3EC]'}"
				>
					<Phone class="h-4 w-4" />
					<span>Concierge Atelier</span>
				</button>
			</div>
		</div>

		<!-- Tab Contents -->
		<div class="mt-8">
			{#if activeTab === 'orders'}
				<!-- Reorder Toast Notification -->
				{#if reorderSuccessMsg}
					<div class="mb-5 flex items-center justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800 shadow-sm animate-in fade-in slide-in-from-top-2">
						<div class="flex items-center gap-2">
							<Check class="h-4 w-4 text-emerald-600 shrink-0" />
							<span>{reorderSuccessMsg}</span>
						</div>
						<a
							href="/keranjang"
							class="font-semibold text-emerald-700 underline hover:text-emerald-900 shrink-0"
						>
							Buka Keranjang &rarr;
						</a>
					</div>
				{/if}

				<!-- Orders List -->
				{#if orders.length === 0}
					<div class="rounded-3xl border border-[#E8DFD0] bg-white px-6 py-16 text-center shadow-sm">
						<Package class="mx-auto h-12 w-12 text-stone-400" />
						<h2 class="mt-4 font-serif text-xl font-bold text-[#1F1810]">
							Belum Ada Riwayat Pesanan
						</h2>
						<p class="mt-1 text-xs text-stone-500 max-w-sm mx-auto">
							Anda belum memiliki transaksi pesanan di Maison Lumina. Mulai jelajahi karya furnitur terbaik kami.
						</p>
						<a
							href="/produk"
							class="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#1F1810] px-6 py-2.5 text-xs font-semibold text-white shadow-sm hover:bg-[#B5652F] transition-colors"
						>
							<span>Mulai Belanja</span>
							<ArrowRight class="h-3.5 w-3.5" />
						</a>
					</div>
				{:else}
					<div class="space-y-6">
						{#each orders as order}
							<div class="rounded-2xl border border-[#E8DFD0] bg-white p-6 shadow-sm">
								<!-- Order Header Bar -->
								<div class="flex flex-col gap-3 border-b border-[#E8DFD0] pb-4 sm:flex-row sm:items-center sm:justify-between">
									<div class="flex items-center gap-3">
										<div>
											<span class="text-[11px] font-semibold text-stone-500 uppercase tracking-wider block">
												Nomor Pesanan
											</span>
											<span class="font-serif text-base font-bold text-[#1F1810]">
												{order.orderNumber}
											</span>
										</div>
										<Badge
											class={
												order.status === 'Selesai'
													? 'bg-emerald-100 text-emerald-800'
													: order.status === 'Dikirim'
													? 'bg-blue-100 text-blue-800'
													: 'bg-amber-100 text-amber-800'
											}
										>
											{order.status}
										</Badge>
									</div>

									<div class="flex items-center gap-4 text-xs text-stone-600">
										<div class="flex items-center gap-1">
											<Clock class="h-3.5 w-3.5 text-stone-400" />
											<span>{order.createdAt ? formatDateId(order.createdAt) : ''}</span>
										</div>
										<span class="font-serif text-base font-bold text-[#1F1810]">
											{formatRupiah(order.total)}
										</span>
									</div>
								</div>

								<!-- Items Preview List -->
								<div class="divide-y divide-[#E8DFD0]/60 py-2">
									{#each order.items as item}
										<div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between py-3">
											<div class="flex items-center gap-3">
												{#if item.product?.images?.[0]?.url}
													<img
														src={item.product.images[0].url}
														alt={item.product.name}
														class="h-12 w-14 rounded-md object-cover border border-[#E8DFD0] bg-[#EDE4D7] shrink-0"
													/>
												{/if}
												<div>
													<span class="font-serif text-xs font-semibold text-[#1F1810] block">
														{item.product?.name || 'Item Furnitur'}
													</span>
													{#if item.variantLabel}
														<span class="text-[11px] text-[#B5652F] font-medium block">
															Varian: {item.variantLabel}
														</span>
													{/if}
													<span class="text-[11px] text-stone-500">
														{item.qty} unit × {formatRupiah(item.priceAtOrder)}
													</span>
												</div>
											</div>

											<div class="flex items-center justify-between sm:justify-end gap-3 pt-2 sm:pt-0 border-t border-dashed border-[#E8DFD0]/60 sm:border-0">
												<span class="font-serif text-xs font-bold text-[#1F1810]">
													{formatRupiah(item.priceAtOrder * item.qty)}
												</span>
												<button
													type="button"
													onclick={() => handleReorderItem(item)}
													class="inline-flex items-center gap-1.5 rounded-lg border border-[#E8DFD0] bg-white px-2.5 py-1.5 text-[11px] font-semibold text-stone-700 hover:border-[#B5652F] hover:text-[#B5652F] transition-colors shadow-2xs"
													title="Tambahkan item ini kembali ke keranjang"
												>
													<RotateCcw class="h-3 w-3 text-[#B5652F]" />
													<span>Beli Lagi</span>
												</button>
											</div>
										</div>
									{/each}
								</div>

								<!-- Order Footer & Action -->
								<div class="flex flex-col gap-3 border-t border-[#E8DFD0] pt-4 sm:flex-row sm:items-center sm:justify-between text-xs">
									<div class="text-stone-600">
										<span>Tujuan: <strong>{order.recipientName}</strong>, {order.shippingAddress}</span>
									</div>

									<div class="flex items-center gap-2">
										<button
											type="button"
											onclick={() => handleReorderAll(order)}
											class="inline-flex items-center gap-1.5 rounded-lg border border-[#1F1810] bg-white px-3.5 py-2 text-xs font-semibold text-[#1F1810] hover:bg-[#F7F3EC] transition-colors shadow-2xs"
											title="Tambahkan seluruh item pesanan ini ke keranjang"
										>
											<RotateCcw class="h-3.5 w-3.5 text-[#B5652F]" />
											<span>Beli Lagi Semua</span>
										</button>
										<a
											href="/checkout/konfirmasi?order={order.orderNumber}"
											class="inline-flex items-center gap-1.5 rounded-lg bg-[#1F1810] px-4 py-2 text-xs font-semibold text-white hover:bg-[#B5652F] transition-colors shadow-xs"
										>
											<span>Lihat E-Invoice</span>
											<ArrowRight class="h-3.5 w-3.5" />
										</a>
									</div>
								</div>
							</div>
						{/each}
					</div>
				{/if}
			{:else if activeTab === 'addresses'}
				<!-- Saved Addresses -->
				<div class="rounded-2xl border border-[#E8DFD0] bg-white p-6 shadow-sm space-y-4">
					<div class="flex items-center justify-between">
						<h2 class="font-serif text-lg font-semibold text-[#1F1810]">
							Buku Alamat Pengiriman
						</h2>
					</div>

					{#if addresses.length > 0}
						<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
							{#each addresses as addr}
								<div class="rounded-xl border border-[#E8DFD0] bg-[#F7F3EC]/50 p-5 space-y-2">
									<div class="flex items-center justify-between">
										<span class="font-serif text-sm font-bold text-[#1F1810]">{addr.isDefault ? 'Alamat Utama' : 'Alamat Pengiriman'}</span>
										{#if addr.isDefault}
											<Badge class="bg-[#1F1810] text-white text-[10px]">Default</Badge>
										{/if}
									</div>
									<p class="text-xs font-semibold text-stone-800">
										{addr.recipient} ({addr.phone})
									</p>
									<p class="text-xs text-stone-600 leading-relaxed">
										{addr.fullAddress}
									</p>
									{#if addr.notes}
										<div class="pt-2 text-[11px] text-stone-500 italic">
											Catatan: {addr.notes}
										</div>
									{/if}
								</div>
							{/each}
						</div>
					{:else}
						<div class="rounded-xl border border-[#E8DFD0] bg-[#F7F3EC]/50 p-5 space-y-2">
							<div class="flex items-center justify-between">
								<span class="font-serif text-sm font-bold text-[#1F1810]">Rumah (Utama)</span>
								<Badge class="bg-[#1F1810] text-white text-[10px]">Default</Badge>
							</div>
							<p class="text-xs font-semibold text-stone-800">
								{user.name} (0812-3456-7890)
							</p>
							<p class="text-xs text-stone-600 leading-relaxed">
								Jl. Kemang Raya No. 45, RT 02 / RW 05, Bangka, Mampang Prapatan, Jakarta Selatan, DKI Jakarta 12730
							</p>
							<div class="pt-2 text-[11px] text-stone-500 italic">
								Catatan: Akses mudah lift barang, konfirmasi 30 menit sebelum pengantaran.
							</div>
						</div>
					{/if}
				</div>
			{:else if activeTab === 'concierge'}
				<!-- Concierge Atelier -->
				<div class="rounded-2xl border border-[#E8DFD0] bg-white p-6 sm:p-8 shadow-sm space-y-6">
					<div class="flex items-center gap-3">
						<div class="flex h-12 w-12 items-center justify-center rounded-full bg-[#B5652F]/10 text-[#B5652F]">
							<Phone class="h-6 w-6" />
						</div>
						<div>
							<h2 class="font-serif text-xl font-bold text-[#1F1810]">
								Layanan Concierge Eksklusif VIP
							</h2>
							<p class="text-xs text-stone-600">
								Konsultasi langsung dengan tim desainer interior &amp; ahli perakitan mebel kami.
							</p>
						</div>
					</div>

					<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
						<div class="rounded-xl border border-[#E8DFD0] p-4 bg-[#F7F3EC]/40 space-y-2">
							<ShieldCheck class="h-5 w-5 text-[#B5652F]" />
							<span class="font-bold text-[#1F1810] block">Garansi Rangka 2 Tahun</span>
							<p class="text-stone-600">Perlindungan struktur kayu solid dan konstruksi purus sambungan.</p>
						</div>

						<div class="rounded-xl border border-[#E8DFD0] p-4 bg-[#F7F3EC]/40 space-y-2">
							<Wrench class="h-5 w-5 text-[#B5652F]" />
							<span class="font-bold text-[#1F1810] block">Perawatan &amp; Oiling Kayu</span>
							<p class="text-stone-600">Panduan dan kit perawatan minyak jati alami agar keindahan kayu abadi.</p>
						</div>

						<div class="rounded-xl border border-[#E8DFD0] p-4 bg-[#F7F3EC]/40 space-y-2">
							<Sparkles class="h-5 w-5 text-[#B5652F]" />
							<span class="font-bold text-[#1F1810] block">Custom Dimensi &amp; Kain</span>
							<p class="text-stone-600">Bisa meminta penyesuaian ukuran khusus untuk ruangan Anda.</p>
						</div>
					</div>

					<div class="border-t border-[#E8DFD0] pt-5">
						<a
							href="https://wa.me/6281234567890?text=Halo%20Maison%20Lumina,%20saya%20member%20VIP%20{user.name}%20ingin%20berkonsultasi"
							target="_blank"
							rel="noreferrer"
							class="inline-flex items-center gap-2 rounded-xl bg-[#1F1810] px-6 py-3 text-xs font-semibold text-white shadow-sm hover:bg-[#B5652F] transition-colors"
						>
							<Phone class="h-4 w-4" />
							<span>Hubungi Konsultan via WhatsApp</span>
							<ArrowRight class="h-3.5 w-3.5" />
						</a>
					</div>
				</div>
			{/if}
		</div>
	</div>
</div>

// src/app/akun/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Gift, ShoppingBag, User, MapPin, Heart, MessageCircle, ChevronRight, Truck, CheckCircle2, ExternalLink, RotateCcw } from 'lucide-react';
import { mockUserProfile, mockOrders } from '@/lib/mockData';
import { formatRupiah, formatDateId } from '@/lib/utils';

const sidebarNav = [
  { key: 'riwayat', label: 'Riwayat Pesanan', icon: ShoppingBag, badge: 3 },
  { key: 'profil', label: 'Profil Pengguna', icon: User },
  { key: 'alamat', label: 'Alamat Pengiriman', icon: MapPin },
  { key: 'wishlist', label: 'Wishlist Tersimpan', icon: Heart },
];

export default function AkunPage() {
  const [activeSection, setActiveSection] = useState('riwayat');
  const [activeOrderFilter, setActiveOrderFilter] = useState('Semua');
  const user = mockUserProfile;

  const filteredOrders = activeOrderFilter === 'Semua'
    ? mockOrders
    : mockOrders.filter((o) => {
        if (activeOrderFilter === 'Dikirim') return o.status === 'Sedang Dikirim';
        if (activeOrderFilter === 'Selesai') return o.status === 'Selesai';
        return true;
      });

  return (
    <div className="page-fade-in">
      {/* ═══════════════ PROFILE BANNER ═══════════════ */}
      <section className="bg-brand-soft border-b border-brand-border">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 rounded-full overflow-hidden bg-brand-border border-2 border-white shadow-soft">
                <img src={user.avatarUrl} alt={user.name} className="w-full h-full object-cover" />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs tracking-[0.15em] uppercase text-brand-accent font-semibold">AKUN MEMBER</span>
                  <span className="px-2 py-0.5 text-[10px] font-bold bg-brand-dark text-white rounded-full">{user.tier} Tier</span>
                </div>
                <h1 className="font-serif text-xl font-bold text-brand-dark">{user.name}</h1>
                <p className="text-xs text-brand-muted">{user.email}</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <p className="text-xs text-brand-muted">Total Poin Loyalitas</p>
                <p className="font-serif text-2xl font-bold text-brand-dark">{user.loyaltyPoints.toLocaleString()} Pts</p>
              </div>
              <button className="px-4 py-2.5 bg-brand-dark text-white text-xs font-semibold rounded-lg hover:bg-brand-hoverDark transition-colors flex items-center gap-1.5">
                <Gift size={14} /> Klaim Reward
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════ CONTENT ═══════════════ */}
      <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex flex-col lg:flex-row gap-8">
          {/* Sidebar */}
          <aside className="lg:w-60 flex-shrink-0 space-y-3">
            {sidebarNav.map((item) => (
              <button
                key={item.key}
                onClick={() => setActiveSection(item.key)}
                className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-colors ${
                  activeSection === item.key
                    ? 'bg-brand-dark text-white'
                    : 'text-brand-muted hover:bg-brand-bg hover:text-brand-dark'
                }`}
              >
                <item.icon size={18} />
                <span className="flex-1 text-left">{item.label}</span>
                {item.badge && (
                  <span className={`text-[10px] font-bold rounded-full w-5 h-5 flex items-center justify-center ${
                    activeSection === item.key ? 'bg-brand-accent text-white' : 'bg-brand-border text-brand-muted'
                  }`}>
                    {item.badge}
                  </span>
                )}
              </button>
            ))}

            {/* Help card */}
            <div className="bg-brand-soft rounded-xl p-4 mt-4">
              <div className="flex items-center gap-2 mb-2">
                <MessageCircle size={16} className="text-brand-accent" />
                <h4 className="font-semibold text-xs text-brand-dark">Butuh Bantuan?</h4>
              </div>
              <p className="text-[11px] text-brand-muted mb-3">
                Concierge interior design & customer care kami siap melayani Anda setiap hari.
              </p>
              <button className="text-xs font-semibold text-brand-accent hover:underline flex items-center gap-1">
                Hubungi via WhatsApp <ChevronRight size={12} />
              </button>
            </div>
          </aside>

          {/* Main content */}
          <div className="flex-1">
            {activeSection === 'riwayat' && (
              <div>
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
                  <div>
                    <h2 className="font-serif text-xl font-bold text-brand-dark mb-1">Riwayat Pesanan</h2>
                    <p className="text-sm text-brand-muted">Lacak pengiriman dan tinjau riwayat pembelian furnitur Anda.</p>
                  </div>
                  <div className="flex gap-2">
                    {['Semua', 'Dikirim', 'Selesai'].map((f) => (
                      <button
                        key={f}
                        onClick={() => setActiveOrderFilter(f)}
                        className={`px-3 py-1.5 text-xs font-medium rounded-full transition-colors ${
                          activeOrderFilter === f
                            ? 'bg-brand-dark text-white'
                            : 'bg-white text-brand-muted border border-brand-border hover:border-brand-dark'
                        }`}
                      >
                        {f}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-4">
                  {filteredOrders.map((order) => {
                    const statusBadge = order.status === 'Sedang Dikirim'
                      ? 'bg-blue-50 text-blue-700'
                      : order.status === 'Selesai'
                      ? 'bg-green-50 text-green-700'
                      : 'bg-yellow-50 text-yellow-700';

                    return (
                      <div key={order.id} className="bg-white rounded-xl border border-brand-border p-5">
                        {/* Order header */}
                        <div className="flex flex-wrap items-center justify-between gap-2 mb-4">
                          <div className="flex items-center gap-3">
                            <span className={`${statusBadge} px-2.5 py-1 text-[11px] font-semibold rounded-full flex items-center gap-1`}>
                              {order.status === 'Selesai' ? <CheckCircle2 size={12} /> : <Truck size={12} />}
                              {order.status === 'Sedang Dikirim' ? 'Sedang Dikirim' : order.status}
                            </span>
                            <div>
                              <p className="text-xs text-brand-muted">No. Pesanan: <span className="text-brand-dark font-medium">{order.orderNumber}</span></p>
                              <p className="text-xs text-brand-dark font-semibold">
                                {order.status === 'Sedang Dikirim'
                                  ? `Estimasi Tiba: ${order.shippingDate ? formatDateId(order.shippingDate) : '-'}`
                                  : `Diterima: ${order.shippingDate ? formatDateId(order.shippingDate) : '-'}`
                                }
                              </p>
                            </div>
                          </div>
                          <div className="text-right">
                            <p className="text-xs text-brand-muted">Total Pembayaran</p>
                            <p className="font-bold text-brand-dark">{formatRupiah(order.total)}</p>
                          </div>
                        </div>

                        {/* Order items */}
                        {order.items.map((item) => (
                          <div key={item.id} className="flex items-center gap-4 py-3 border-t border-brand-border">
                            <div className="w-16 h-16 rounded-lg overflow-hidden bg-brand-soft flex-shrink-0">
                              <img src={item.product.images[0]?.url} alt={item.product.name} className="w-full h-full object-cover" />
                            </div>
                            <div className="flex-1 min-w-0">
                              <h4 className="text-sm font-semibold text-brand-dark">{item.product.name}</h4>
                              <p className="text-xs text-brand-muted">{item.variantLabel} • {item.qty} Unit</p>
                              {order.status === 'Sedang Dikirim' && (
                                <p className="text-[11px] text-brand-accent font-semibold mt-0.5">Kurir: Maison White-Glove Logistics</p>
                              )}
                              {order.status === 'Selesai' && (
                                <p className="text-[11px] text-green-600 font-semibold mt-0.5">
                                  {order.total > 10000000 ? 'Pemasangan Gratis Selesai' : 'Garansi 1 Tahun Aktif'}
                                </p>
                              )}
                            </div>
                            <div className="flex gap-2">
                              <Link
                                href="/checkout/konfirmasi"
                                className="px-3 py-1.5 text-xs font-medium border border-brand-border rounded-lg text-brand-dark hover:bg-brand-bg transition-colors"
                              >
                                Detail Pesanan
                              </Link>
                              {order.status === 'Sedang Dikirim' ? (
                                <button className="px-3 py-1.5 text-xs font-semibold bg-brand-dark text-white rounded-lg hover:bg-brand-hoverDark transition-colors">
                                  Lacak Kurir
                                </button>
                              ) : (
                                <button className="px-3 py-1.5 text-xs font-semibold bg-brand-dark text-white rounded-lg hover:bg-brand-hoverDark transition-colors flex items-center gap-1">
                                  <RotateCcw size={12} /> Beli Lagi
                                </button>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {activeSection === 'profil' && (
              <div className="bg-white rounded-xl border border-brand-border p-6">
                <h2 className="font-serif text-xl font-bold text-brand-dark mb-6">Profil Pengguna</h2>
                <div className="space-y-4 max-w-md">
                  <div>
                    <label className="text-xs text-brand-muted mb-1 block">Nama Lengkap</label>
                    <input type="text" defaultValue={user.name} className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg focus:outline-none focus:border-brand-accent" />
                  </div>
                  <div>
                    <label className="text-xs text-brand-muted mb-1 block">Email</label>
                    <input type="email" defaultValue={user.email} className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg focus:outline-none focus:border-brand-accent" />
                  </div>
                  <div>
                    <label className="text-xs text-brand-muted mb-1 block">No. Telepon</label>
                    <input type="text" defaultValue="+62 812-3456-7890" className="w-full px-4 py-2.5 text-sm border border-brand-border rounded-lg focus:outline-none focus:border-brand-accent" />
                  </div>
                  <button className="px-5 py-2.5 bg-brand-dark text-white text-sm font-semibold rounded-lg hover:bg-brand-hoverDark transition-colors">
                    Simpan Perubahan
                  </button>
                </div>
              </div>
            )}

            {activeSection === 'alamat' && (
              <div className="bg-white rounded-xl border border-brand-border p-6">
                <h2 className="font-serif text-xl font-bold text-brand-dark mb-6">Alamat Pengiriman</h2>
                {user.addresses.map((addr) => (
                  <div key={addr.id} className="p-4 border border-brand-border rounded-lg mb-3">
                    <div className="flex items-center gap-2 mb-2">
                      <MapPin size={14} className="text-brand-accent" />
                      <span className="text-sm font-semibold text-brand-dark">{addr.recipient}</span>
                      {addr.isDefault && <span className="text-[10px] bg-brand-accent text-white px-2 py-0.5 rounded-full font-semibold">Utama</span>}
                    </div>
                    <p className="text-xs text-brand-muted">{addr.phone}</p>
                    <p className="text-xs text-brand-muted">{addr.fullAddress}</p>
                    {addr.notes && <p className="text-xs text-brand-muted italic mt-1">Catatan: {addr.notes}</p>}
                  </div>
                ))}
                <button className="px-4 py-2 text-sm font-semibold border border-brand-border rounded-lg text-brand-dark hover:bg-brand-bg transition-colors">
                  + Tambah Alamat Baru
                </button>
              </div>
            )}

            {activeSection === 'wishlist' && (
              <div className="bg-white rounded-xl border border-brand-border p-6 text-center">
                <Heart size={40} className="mx-auto text-brand-border mb-4" />
                <h3 className="font-serif text-lg font-bold text-brand-dark mb-2">Lihat Wishlist Anda</h3>
                <p className="text-sm text-brand-muted mb-4">Kelola produk favorit yang tersimpan di wishlist Anda.</p>
                <Link href="/wishlist" className="inline-flex items-center gap-2 px-5 py-2.5 bg-brand-dark text-white text-sm font-semibold rounded-lg hover:bg-brand-hoverDark transition-colors">
                  Buka Wishlist <ChevronRight size={14} />
                </Link>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
