// src/lib/components/layout/Header.svelte
<script lang="ts">
	import { cartStore } from '$lib/stores/cart.svelte';
	import { wishlistStore } from '$lib/stores/wishlist.svelte';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import * as Sheet from '$lib/components/ui/sheet';
	import { Badge } from '$lib/components/ui/badge';
	import { goto } from '$app/navigation';

	import Search from '@lucide/svelte/icons/search';
	import ShoppingBag from '@lucide/svelte/icons/shopping-bag';
	import Heart from '@lucide/svelte/icons/heart';
	import User from '@lucide/svelte/icons/user';
	import Menu from '@lucide/svelte/icons/menu';
	import ChevronDown from '@lucide/svelte/icons/chevron-down';
	import Sofa from '@lucide/svelte/icons/sofa';
	import Bed from '@lucide/svelte/icons/bed';
	import Utensils from '@lucide/svelte/icons/utensils';
	import Briefcase from '@lucide/svelte/icons/briefcase';
	import Lamp from '@lucide/svelte/icons/lamp';
	import ArrowRight from '@lucide/svelte/icons/arrow-right';
	import X from '@lucide/svelte/icons/x';
	import Phone from '@lucide/svelte/icons/phone';
	import Compass from '@lucide/svelte/icons/compass';
	import Hammer from '@lucide/svelte/icons/hammer';

	let isScrolled = $state(false);
	let isMobileOpen = $state(false);
	let isSearchOpen = $state(false);
	let searchQuery = $state('');

	function handleScroll() {
		if (typeof window !== 'undefined') {
			isScrolled = window.scrollY > 20;
		}
	}

	function handleSearchSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (searchQuery.trim()) {
			goto(`/produk?q=${encodeURIComponent(searchQuery.trim())}`);
			isSearchOpen = false;
			searchQuery = '';
		}
	}

	const roomCategories = [
		{
			name: 'Ruang Tamu',
			slug: 'ruang-tamu',
			desc: 'Sofa modular, armchair & meja kopi jati',
			icon: Sofa
		},
		{
			name: 'Kamar Tidur',
			slug: 'kamar-tidur',
			desc: 'Rangka tempat tidur & nakas minimalis',
			icon: Bed
		},
		{
			name: 'Ruang Makan',
			slug: 'ruang-makan',
			desc: 'Meja makan solid & kursi makan kurasi',
			icon: Utensils
		},
		{
			name: 'Ruang Kerja',
			slug: 'ruang-kerja',
			desc: 'Meja kerja kayu jati & rak buku arsitektural',
			icon: Briefcase
		},
		{
			name: 'Pencahayaan & Aksesori',
			slug: 'pencahayaan',
			desc: 'Lampu gantung tembaga & dekorasi organik',
			icon: Lamp
		}
	];
</script>

<svelte:window onscroll={handleScroll} />

<header
	class={`sticky top-0 z-40 w-full transition-all duration-300 ${
		isScrolled
			? 'bg-stone-warm/95 backdrop-blur-md shadow-sm border-b border-border/80 py-3'
			: 'bg-stone-warm border-b border-border py-4'
	}`}
>
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between">
		<!-- Left: Mobile Menu & Desktop Navigation -->
		<div class="flex items-center gap-6">
			<!-- Mobile Hamburger Sheet -->
			<div class="lg:hidden">
				<Sheet.Root bind:open={isMobileOpen}>
					<Sheet.Trigger
						class="inline-flex items-center justify-center p-2 text-espresso hover:bg-sand/40 rounded-md transition-colors"
						aria-label="Buka menu navigasi"
					>
						<Menu class="w-5 h-5" />
					</Sheet.Trigger>
					<Sheet.Content side="left" class="w-[85vw] max-w-[340px] sm:w-[380px] bg-stone-warm border-r border-border p-5 sm:p-6 overflow-y-auto">
						<Sheet.Header class="text-left border-b border-border pb-4">
							<div class="flex items-center gap-3">
								<div class="w-8 h-8 rounded-full bg-espresso text-stone-warm flex items-center justify-center font-serif text-sm font-bold shadow-sm shrink-0">
									ML
								</div>
								<div>
									<Sheet.Title class="font-serif text-base sm:text-lg tracking-wider font-semibold text-espresso">
										MAISON LUMINA
									</Sheet.Title>
									<Sheet.Description class="text-[10px] sm:text-xs text-muted-foreground tracking-widest uppercase">
										Atelier &amp; Meubel Indonesia
									</Sheet.Description>
								</div>
							</div>
						</Sheet.Header>

						<!-- Mobile Search Input -->
						<div class="pt-4">
							<form
								onsubmit={(e) => {
									handleSearchSubmit(e);
									isMobileOpen = false;
								}}
								class="relative flex items-center"
							>
								<input
									type="text"
									bind:value={searchQuery}
									placeholder="Cari sofa, jati, meja..."
									class="w-full h-9 pl-8 pr-3 text-xs bg-white border border-border rounded-lg focus:outline-none focus:border-terracotta"
								/>
								<Search class="w-3.5 h-3.5 text-muted-foreground absolute left-2.5 top-2.5 pointer-events-none" />
							</form>
						</div>

						<!-- Mobile Nav Links -->
						<div class="py-4 sm:py-6 space-y-5 sm:space-y-6">
							<div>
								<span class="text-xs font-semibold text-muted-foreground uppercase tracking-widest block mb-2 sm:mb-3">
									Koleksi Ruangan
								</span>
								<div class="space-y-1">
									{#each roomCategories as category}
										{@const CategoryIcon = category.icon}
										<a
											href={`/produk?kategori=${category.slug}`}
											onclick={() => (isMobileOpen = false)}
											class="flex items-center gap-3 px-3 py-2 rounded-md text-sm text-espresso hover:bg-sand/60 transition-colors group"
										>
											<CategoryIcon class="w-4 h-4 text-terracotta group-hover:scale-110 transition-transform shrink-0" />
											<div class="flex-1">
												<div class="font-medium">{category.name}</div>
												<div class="text-[11px] text-muted-foreground">{category.desc}</div>
											</div>
										</a>
									{/each}
									<a
										href="/produk"
										onclick={() => (isMobileOpen = false)}
										class="flex items-center justify-between px-3 py-2.5 mt-2 rounded-md text-xs font-semibold text-terracotta hover:bg-terracotta/10 transition-colors"
									>
										<span>Jelajahi Semua Produk</span>
										<ArrowRight class="w-3.5 h-3.5" />
									</a>
								</div>
							</div>

							<div class="border-t border-border pt-4">
								<span class="text-xs font-semibold text-muted-foreground uppercase tracking-widest block mb-3">
									Eksplorasi Atelier
								</span>
								<div class="space-y-1">
									<a
										href="/craftsmanship"
										onclick={() => (isMobileOpen = false)}
										class="flex items-center gap-3 px-3 py-2 rounded-md text-sm text-espresso hover:bg-sand/60"
									>
										<Hammer class="w-4 h-4 text-terracotta shrink-0" />
										<span>Craftsmanship &amp; Material</span>
									</a>
									<a
										href="/room-planner"
										onclick={() => (isMobileOpen = false)}
										class="flex items-center gap-3 px-3 py-2 rounded-md text-sm text-espresso hover:bg-sand/60"
									>
										<Compass class="w-4 h-4 text-terracotta shrink-0" />
										<span>Interactive Room Planner</span>
									</a>
									<a
										href="/tentang-kami"
										onclick={() => (isMobileOpen = false)}
										class="flex items-center gap-3 px-3 py-2 rounded-md text-sm text-espresso hover:bg-sand/60"
									>
										<span>Tentang Maison Lumina</span>
									</a>
								</div>
							</div>

							<div class="border-t border-border pt-4 space-y-2">
								<a
									href="/wishlist"
									onclick={() => (isMobileOpen = false)}
									class="flex items-center justify-between px-3 py-2 text-sm text-espresso hover:bg-sand/60 rounded-md transition-colors"
								>
									<span class="flex items-center gap-2.5">
										<Heart class="w-4 h-4 text-muted-foreground shrink-0" />
										Daftar Keinginan
									</span>
									{#if wishlistStore.itemCount > 0}
										<Badge class="bg-terracotta text-white text-[10px] px-2 py-0.5 border-none font-bold">
											{wishlistStore.itemCount}
										</Badge>
									{/if}
								</a>
								<a
									href="/keranjang"
									onclick={() => (isMobileOpen = false)}
									class="flex items-center justify-between px-3 py-2 text-sm text-espresso hover:bg-sand/60 rounded-md transition-colors"
								>
									<span class="flex items-center gap-2.5">
										<ShoppingBag class="w-4 h-4 text-muted-foreground shrink-0" />
										Keranjang Belanja
									</span>
									{#if cartStore.itemCount > 0}
										<Badge class="bg-espresso text-stone-warm text-[10px] px-2 py-0.5 border-none font-bold">
											{cartStore.itemCount}
										</Badge>
									{/if}
								</a>
								<a
									href="/akun"
									onclick={() => (isMobileOpen = false)}
									class="flex items-center justify-between px-3 py-2 text-sm text-espresso hover:bg-sand/60 rounded-md"
								>
									<span class="flex items-center gap-2.5">
										<User class="w-4 h-4 text-muted-foreground shrink-0" />
										Akun Saya
									</span>
									<span class="text-xs text-muted-foreground">Profil &amp; Pesanan</span>
								</a>
								<a
									href="https://wa.me/6281234567890"
									target="_blank"
									rel="noreferrer"
									class="flex items-center gap-2.5 px-3 py-2 text-xs font-medium text-terracotta bg-terracotta/10 rounded-md hover:bg-terracotta/20 transition-colors"
								>
									<Phone class="w-3.5 h-3.5 shrink-0" />
									Hubungi WhatsApp Concierge
								</a>
							</div>
						</div>
					</Sheet.Content>
				</Sheet.Root>
			</div>

			<!-- Desktop Main Menu Links -->
			<nav class="hidden lg:flex items-center gap-8 text-sm font-medium text-espresso/90">
				<a href="/" class="hover:text-terracotta transition-colors py-1">
					Beranda
				</a>

				<!-- Koleksi DropdownMenu -->
				<DropdownMenu.Root>
					<DropdownMenu.Trigger class="inline-flex items-center gap-1 hover:text-terracotta transition-colors py-1 outline-none group cursor-pointer">
						<span>Koleksi</span>
						<ChevronDown class="w-3.5 h-3.5 text-muted-foreground group-hover:text-terracotta transition-transform group-data-[state=open]:rotate-180" />
					</DropdownMenu.Trigger>
					<DropdownMenu.Content class="w-72 bg-white/98 backdrop-blur-md border border-border shadow-xl p-2 rounded-lg" align="start">
						<DropdownMenu.Label class="text-[11px] font-semibold tracking-wider text-muted-foreground uppercase px-2 py-1.5">
							Kurasi Berdasarkan Ruang
						</DropdownMenu.Label>
						<DropdownMenu.Separator class="bg-border/60" />
						{#each roomCategories as category}
							{@const CategoryIcon = category.icon}
							<DropdownMenu.Item
								onSelect={() => goto(`/produk?kategori=${category.slug}`)}
								class="flex items-start gap-3 px-2.5 py-2 rounded-md hover:bg-sand/60 cursor-pointer transition-colors group"
							>
								<CategoryIcon class="w-4 h-4 text-terracotta shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
								<div>
									<div class="text-xs font-semibold text-espresso">{category.name}</div>
									<div class="text-[10px] text-muted-foreground leading-tight">{category.desc}</div>
								</div>
							</DropdownMenu.Item>
						{/each}
						<DropdownMenu.Separator class="bg-border/60" />
						<DropdownMenu.Item
							onSelect={() => goto('/produk')}
							class="flex items-center justify-between px-2.5 py-2 text-xs font-medium text-terracotta hover:bg-terracotta/10 rounded-md cursor-pointer transition-colors"
						>
							<span>Lihat Semua Katalog</span>
							<ArrowRight class="w-3 h-3" />
						</DropdownMenu.Item>
					</DropdownMenu.Content>
				</DropdownMenu.Root>

				<a href="/craftsmanship" class="hover:text-terracotta transition-colors py-1">
					Craftsmanship
				</a>

				<a href="/room-planner" class="hover:text-terracotta transition-colors py-1 flex items-center gap-1">
					<span>Room Planner</span>
					<span class="px-1.5 py-0.5 text-[9px] font-bold tracking-wide uppercase bg-terracotta text-white rounded">
						3D Beta
					</span>
				</a>

				<a href="/tentang-kami" class="hover:text-terracotta transition-colors py-1">
					Tentang Kami
				</a>
			</nav>
		</div>

		<!-- Center: Brand Logo & Monogram -->
		<div class="flex items-center justify-center text-center">
			<a href="/" class="group flex items-center gap-2 sm:gap-3">
				<div class="w-8 h-8 sm:w-9 sm:h-9 rounded-full bg-espresso text-stone-warm flex items-center justify-center font-serif text-sm sm:text-base font-bold shadow-sm group-hover:bg-terracotta transition-colors shrink-0">
					ML
				</div>
				<div class="text-left sm:text-center">
					<span class="font-serif text-sm min-[380px]:text-base sm:text-xl font-bold tracking-[0.10em] min-[380px]:tracking-[0.14em] sm:tracking-[0.18em] text-espresso uppercase block leading-none">
						MAISON LUMINA
					</span>
					<span class="text-[8px] min-[380px]:text-[9px] sm:text-[10px] tracking-[0.18em] sm:tracking-[0.25em] text-muted-foreground uppercase block font-medium mt-0.5 sm:mt-1">
						Atelier &amp; Meubel
					</span>
				</div>
			</a>
		</div>

		<!-- Right: Action Icons (Search, Wishlist, Cart, Profile) -->
		<div class="flex items-center gap-0.5 sm:gap-2">
			<!-- Quick Search Toggle / Input -->
			{#if isSearchOpen}
				<form
					onsubmit={handleSearchSubmit}
					class="relative hidden sm:flex items-center animate-in fade-in zoom-in-95 duration-200"
				>
					<input
						type="text"
						bind:value={searchQuery}
						placeholder="Cari sofa, jati, meja..."
						class="w-48 lg:w-60 h-8 pl-8 pr-7 text-xs bg-white border border-border rounded-full focus:outline-none focus:border-terracotta shadow-inner"
					/>
					<Search class="w-3.5 h-3.5 text-muted-foreground absolute left-2.5 top-2.5 pointer-events-none" />
					<button
						type="button"
						onclick={() => (isSearchOpen = false)}
						class="absolute right-2 text-muted-foreground hover:text-espresso"
						aria-label="Tutup pencarian"
					>
						<X class="w-3.5 h-3.5" />
					</button>
				</form>
			{:else}
				<button
					type="button"
					class="p-2 text-espresso hover:bg-sand/40 rounded-full transition-colors hidden sm:flex items-center justify-center"
					onclick={() => (isSearchOpen = true)}
					aria-label="Cari produk"
				>
					<Search class="w-4 h-4" />
				</button>
			{/if}

			<!-- Wishlist Link & Badge -->
			<a
				href="/wishlist"
				class="relative p-2 text-espresso hover:text-terracotta hover:bg-sand/40 rounded-full transition-colors flex items-center justify-center"
				aria-label="Daftar Keinginan"
			>
				<Heart class="w-4 h-4 sm:w-5 sm:h-5" />
				{#if wishlistStore.itemCount > 0}
					<Badge
						variant="destructive"
						class="absolute -top-1 -right-1 h-4 min-w-4 px-1 text-[10px] flex items-center justify-center rounded-full bg-terracotta text-white font-bold border-2 border-stone-warm shadow-sm"
					>
						{wishlistStore.itemCount}
					</Badge>
				{/if}
			</a>

			<!-- Cart Link & Badge -->
			<a
				href="/keranjang"
				class="relative p-2 text-espresso hover:text-terracotta hover:bg-sand/40 rounded-full transition-colors flex items-center justify-center"
				aria-label="Keranjang Belanja"
			>
				<ShoppingBag class="w-4 h-4 sm:w-5 sm:h-5" />
				{#if cartStore.itemCount > 0}
					<Badge
						variant="default"
						class="absolute -top-1 -right-1 h-4 min-w-4 px-1 text-[10px] flex items-center justify-center rounded-full bg-espresso text-white font-bold border-2 border-stone-warm shadow-sm"
					>
						{cartStore.itemCount}
					</Badge>
				{/if}
			</a>

			<!-- Profile / Account -->
			<a
				href="/akun"
				class="p-2 text-espresso hover:text-terracotta hover:bg-sand/40 rounded-full transition-colors flex items-center justify-center"
				aria-label="Akun Saya"
			>
				<User class="w-4 h-4 sm:w-5 sm:h-5" />
			</a>
		</div>
	</div>
</header>

// src/components/layout/Header.tsx
"use client";

import * as React from "react";
import Link from "next/link";
import { Search, Heart, ShoppingBag, User, Menu } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import NavDropdown from "@/components/layout/NavDropdown";
import { useCartStore } from "@/store/cartStore";
import { useWishlistStore } from "@/store/wishlistStore";

const navLinks = [
  { label: "Beranda", href: "/" },
  { label: "Koleksi", href: "/koleksi" },
  { label: "Craftsmanship", href: "/craftsmanship" },
  { label: "Room Planner", href: "/room-planner" },
  { label: "Sale", href: "/koleksi?sale=true" },
];

const roomCategories = [
  { label: "Ruang Tamu", href: "/koleksi?room=ruang-tamu" },
  { label: "Kamar Tidur", href: "/koleksi?room=kamar-tidur" },
  { label: "Ruang Makan", href: "/koleksi?room=ruang-makan" },
  { label: "Ruang Kerja", href: "/koleksi?room=ruang-kerja" },
];

export default function Header() {
  const [mounted, setMounted] = React.useState(false);
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const [searchQuery, setSearchQuery] = React.useState("");
  const cartStoreCount = useCartStore((s) =>
    s.items ? s.items.reduce((sum, i) => sum + i.qty, 0) : 0
  );
  const wishlistStoreCount = useWishlistStore((s) =>
    s.items ? s.items.length : 0
  );

  React.useEffect(() => {
    setMounted(true);
  }, []);

  const wishlistCount = mounted ? wishlistStoreCount : 0;
  const cartCount = mounted ? cartStoreCount : 0;

  return (
    <header className="sticky top-0 z-40 w-full bg-background/95 backdrop-blur border-b border-border-soft">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16 sm:h-[70px]">
          {/* Mobile hamburger menu (Sheet trigger on left) */}
          <div className="flex items-center lg:hidden">
            <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
              <SheetTrigger asChild>
                <button
                  type="button"
                  className="p-2 -ml-2 text-text-primary hover:text-accent transition-colors focus:outline-none"
                  aria-label="Buka menu"
                >
                  <Menu size={22} />
                </button>
              </SheetTrigger>
              <SheetContent side="left" className="w-[300px] sm:w-[360px] p-6 bg-background flex flex-col justify-between overflow-y-auto">
                <div>
                  <SheetHeader className="text-left mb-6">
                    <SheetTitle className="flex items-center gap-2.5">
                      <div className="w-8 h-8 bg-[#D8D2C4] rounded flex items-center justify-center text-xs font-semibold text-text-secondary">
                        ML
                      </div>
                      <span className="font-serif text-lg font-bold tracking-wider text-dark">
                        MAISON LUMINA
                      </span>
                    </SheetTitle>
                  </SheetHeader>

                  {/* Mobile Search */}
                  <div className="relative mb-6">
                    <Input
                      type="text"
                      placeholder="Cari furniture..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="pr-9 h-10 text-sm bg-white border-border-soft rounded-lg"
                    />
                    <Search
                      size={16}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-text-secondary pointer-events-none"
                    />
                  </div>

                  {/* Mobile Navigation List */}
                  <nav className="flex flex-col space-y-1">
                    <Link
                      href="/"
                      onClick={() => setMobileOpen(false)}
                      className="px-3 py-2.5 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5 transition-colors"
                    >
                      Beranda
                    </Link>

                    {/* Shop by Room sub-items */}
                    <div className="px-3 py-2">
                      <p className="text-xs font-semibold uppercase tracking-wider text-text-secondary/80 mb-2">
                        Shop by Room
                      </p>
                      <div className="pl-2 space-y-1 border-l border-border-soft">
                        {roomCategories.map((room) => (
                          <Link
                            key={room.label}
                            href={room.href}
                            onClick={() => setMobileOpen(false)}
                            className="block px-2.5 py-1.5 rounded text-sm text-text-secondary hover:text-accent hover:bg-dark/5 transition-colors"
                          >
                            {room.label}
                          </Link>
                        ))}
                      </div>
                    </div>

                    <Link
                      href="/koleksi"
                      onClick={() => setMobileOpen(false)}
                      className="px-3 py-2.5 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5 transition-colors"
                    >
                      Koleksi
                    </Link>
                    <Link
                      href="/craftsmanship"
                      onClick={() => setMobileOpen(false)}
                      className="px-3 py-2.5 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5 transition-colors"
                    >
                      Craftsmanship
                    </Link>
                    <Link
                      href="/room-planner"
                      onClick={() => setMobileOpen(false)}
                      className="px-3 py-2.5 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5 transition-colors"
                    >
                      Room Planner
                    </Link>
                    <Link
                      href="/koleksi?sale=true"
                      onClick={() => setMobileOpen(false)}
                      className="px-3 py-2.5 rounded-md text-sm font-medium text-accent hover:bg-dark/5 transition-colors"
                    >
                      Sale
                    </Link>
                  </nav>
                </div>

                {/* Mobile Bottom User Links */}
                <div className="pt-6 border-t border-border-soft mt-6 space-y-2">
                  <Link
                    href="/wishlist"
                    onClick={() => setMobileOpen(false)}
                    className="flex items-center justify-between px-3 py-2 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5"
                  >
                    <span className="flex items-center gap-2">
                      <Heart size={16} /> Wishlist
                    </span>
                    {wishlistCount > 0 && (
                      <Badge variant="secondary" className="bg-accent text-white text-xs">
                        {wishlistCount}
                      </Badge>
                    )}
                  </Link>
                  <Link
                    href="/keranjang"
                    onClick={() => setMobileOpen(false)}
                    className="flex items-center justify-between px-3 py-2 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5"
                  >
                    <span className="flex items-center gap-2">
                      <ShoppingBag size={16} /> Keranjang
                    </span>
                    {cartCount > 0 && (
                      <Badge variant="secondary" className="bg-accent text-white text-xs">
                        {cartCount}
                      </Badge>
                    )}
                  </Link>
                  <Link
                    href="/akun"
                    onClick={() => setMobileOpen(false)}
                    className="flex items-center gap-2 px-3 py-2 rounded-md text-sm font-medium text-text-primary hover:bg-dark/5"
                  >
                    <User size={16} /> Akun Saya
                  </Link>
                </div>
              </SheetContent>
            </Sheet>
          </div>

          {/* Left: Logo placeholder + Brand name */}
          <div className="flex items-center">
            <Link href="/" className="flex items-center gap-2.5 group">
              <div className="w-8 h-8 sm:w-9 sm:h-9 bg-[#D8D2C4] border border-border-soft rounded flex items-center justify-center text-xs font-semibold text-text-secondary shadow-sm">
                ML
              </div>
              <span className="font-serif text-lg sm:text-xl font-bold tracking-wider text-dark group-hover:text-accent transition-colors">
                MAISON LUMINA
              </span>
            </Link>
          </div>

          {/* Center: Desktop Navigation */}
          <nav className="hidden lg:flex items-center gap-6">
            <Link
              href="/"
              className="text-sm font-medium text-text-primary hover:text-accent transition-colors"
            >
              Beranda
            </Link>
            <NavDropdown />
            <Link
              href="/koleksi"
              className="text-sm font-medium text-text-primary hover:text-accent transition-colors"
            >
              Koleksi
            </Link>
            <Link
              href="/craftsmanship"
              className="text-sm font-medium text-text-primary hover:text-accent transition-colors"
            >
              Craftsmanship
            </Link>
            <Link
              href="/room-planner"
              className="text-sm font-medium text-text-primary hover:text-accent transition-colors"
            >
              Room Planner
            </Link>
            <Link
              href="/koleksi?sale=true"
              className="text-sm font-medium text-accent hover:underline transition-all"
            >
              Sale
            </Link>
          </nav>

          {/* Right: Search Input + 3 Icons */}
          <div className="flex items-center gap-2 sm:gap-3">
            {/* Search Input with right-aligned icon */}
            <div className="relative hidden md:block w-44 xl:w-56">
              <Input
                type="text"
                placeholder="Cari furniture..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pr-8 h-9 text-xs bg-white/80 border-border-soft rounded-full focus-visible:ring-dark"
              />
              <Search
                size={15}
                className="absolute right-2.5 top-1/2 -translate-y-1/2 text-text-secondary pointer-events-none"
              />
            </div>

            {/* Wishlist Icon with Badge */}
            <Link
              href="/wishlist"
              className="relative p-2 text-text-primary hover:text-accent transition-colors"
              aria-label="Wishlist"
            >
              <Heart size={20} />
              {wishlistCount > 0 && (
                <Badge
                  variant="secondary"
                  className="absolute -top-0.5 -right-0.5 h-4 min-w-[16px] px-1 text-[10px] font-bold flex items-center justify-center rounded-full bg-accent text-white border-none"
                >
                  {wishlistCount}
                </Badge>
              )}
            </Link>

            {/* Cart Icon with Badge */}
            <Link
              href="/keranjang"
              className="relative p-2 text-text-primary hover:text-accent transition-colors"
              aria-label="Keranjang"
            >
              <ShoppingBag size={20} />
              {cartCount > 0 && (
                <Badge
                  variant="secondary"
                  className="absolute -top-0.5 -right-0.5 h-4 min-w-[16px] px-1 text-[10px] font-bold flex items-center justify-center rounded-full bg-accent text-white border-none"
                >
                  {cartCount}
                </Badge>
              )}
            </Link>

            {/* Account Avatar */}
            <Link href="/akun" aria-label="Akun" className="ml-1">
              <Avatar className="h-8 w-8 sm:h-9 sm:w-9 bg-dark text-white cursor-pointer hover:opacity-90 transition-opacity shadow-sm">
                <AvatarFallback className="bg-dark text-white">
                  <User size={16} />
                </AvatarFallback>
              </Avatar>
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}
